### ISSUE TITLE
No 1.18.2 update

### ISSUE THREAD

**Issue by XxsjrapsxX** [Tyfyter/SimpleStealth#1]
It seems that you left the mod off on 1.17.1, but this is a rather uncommon version to see mods for and makes it hard to produce a modpack with this mod. A 1.18.2 version would be a perfect place to end this off as it has recently become one of the most modded recent versions. Any consideration would be appreciated!

**Comment by Tyfyter** [comment]
It appears that the reason for this is that I was attempting to improve the mod's functionality while updating it to 1.18, encountered some difficulties trying to make the damage boost apply even on crits, and proceeded to entirely forget about Minecraft modding altogether, I have uploaded what should be a fully functional 1.18.2 version to curseforge, and the latest commit also includes said version;
Further updates will come when I figure out how to use Fabric more effectively.

**Comment by XxsjrapsxX** [comment]
I thank you for adressing this issue, i understand that mod developing can be hard as all hell, as simple coding itself can be painfully annoying. Its great to see at the very least it isnt abandoned as of yet, im sure you can get the hang of fabric soon, a lot of devs say its much easier than forge. Might i suggest looking for places where mod devs discuss modding and provide help to one another, if there isn't one it would a good idea to see if its possible to create one. I look forward to your future updates and mods!
